### ISSUE TITLE
Add a mappings from non-obfuscated to obfuscated names

### ISSUE THREAD

**Issue by C0D3-M4513R** [PlagueVRC/AntiRip#16]
For use with OSC you currently have the Obfuscator settings that allow you to not rename a couple things.
For advanced Users it might be possible to just lookup a mapping from an Obfuscated name to the un-obfuscated name in a custom program. 

Then as an advanced user you do not need to exclude really any names manually, because even if you use OSC, you can just use the provided mappings.

I've worked with [ProGuard](https://www.guardsquare.com/manual/home) (Java obfuscator) before and they also provide the mappings. It is immensely helpful to have the mappings from non-obfuscated to obfuscated or reverse for the creator.
E.g.: I made a mistake in my controller and want some more information. So I go open the Debug Overlay and look at my parameters/Animators with the help of the mappings. Without the mappings the Debug Overlay is of no use.

**Comment by MistressPlague** [comment]
Beyond few OSC tools support this, so it is so niche it is not worth the development.
Most don't even let you specify a custom OSC param name for a monitored value.

I do understand the debugging however, for this use case it is only useful for a developer, which also is a niche. I feel this could add more confusing than positive outcome, but I still may develop it; being sure to not make the file in a easy to find location to avoid general users finding it confused.

Thanks.

**Comment by MistressPlague** [comment]
Yes, as that is how issues work. If the issue is solved, it is marked as completed. This is marked as unknown, hence the wording of "it is not worth the development, I still may develop it however"

Because there is no guarantee, this is marked as completed.

Issues are for issues, not so much ideas, so completed issue != development complete.
People simply use issues as a bodged option as not too many other options for suggestions exist.

**Comment by MistressPlague** [comment]
Although, to dig into the meme-ness, I already have finished development of it. Testing now.

**Comment by MistressPlague** [comment]
You just deserialize to this type: https://github.com/PlagueVRC/AntiRip/blob/main/Scripts/Obfuscator.cs#L30
