### ISSUE TITLE
Suggestion: Experimentation with using Normal values for Public Key

### ISSUE THREAD

**Issue by BowmanFox** [PlagueVRC/AntiRip#18]
Hashing vertices is genius. However, I am curious, what about if you use Normals on a model to decrypt the avatar. What do you think the output and issues with this would be? And the upsides compared to shaders and/or vertices. If not for decrypting, what other ways could it be used to improve usability while offering little to no compromise?

If this hasn't already been tried, I'd love to see the results, and if it is anymore efficient. If it is redundant or not a good idea for reasons outside of my expertise, then let me know.

**Comment by MistressPlague** [comment]
Normals being used means the mesh would still be intact.
Re-doing normals in blender is nothing compared to re-doing the entire mesh from a wrecked state.

**Comment by MistressPlague** [comment]
It's worth making sure you're following the right context.
A normal map is effectively a lighting map. It is nothing to do with the physical mesh, but instead the UV mapping's lighting handling.

**Comment by MistressPlague** [comment]
Let's move to discord for discussion, as using this notifies the discord on each change. We can post to here if there's anything further, such as this being viable for a use case.
