### ISSUE TITLE
Undisposed RNGCryptoServiceProvider

### ISSUE THREAD

**Issue by w200338** [PlagueVRC/AntiRip#3]
Hey as a programmer myself I saw a few little bumps in the code which I think could be improved and/or made more secure. I was looking over what was in it and noticed these things.

In the KannaProteccData class an RNGCryptoServiceProvider is used, but it doesn't get disposed of. This will lead to underlying resources which it uses to not be disposed. Luckily it can be easily fixed by wrapping the RNGCryptoServiceProvider in a using statement.

```cs
void Shuffle<T>(IList<T> list)
{
    using (var provider = new RNGCryptoServiceProvider())
    {
        var n = list.Count;
        while (n > 1)
        {
            ...
        }
    }
}
```

- [Location in source code](https://github.com/PlagueVRC/AntiRip/blob/446740b1e605cef186090b29aea7b65466ea81be/Scripts/KannaProteccMaterial.cs#L469)
- [Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?view=netstandard-2.0#remarks)

It may be a good idea to use the RNGCryptoServiceProvider to generate the random encryption key inside the KannaProteccRoot.GenerateNewKey method like this:
```cs
public void GenerateNewKey()
{
    using (var rng = new RNGCryptoServiceProvider())
    {
        byte[] randomBytes = new byte[4];
        rng.GetBytes(randomBytes);

        for (int i = 0; i < 4; i++)
        {
            for (int j = 0; j < 8; j++)
            {
                _bitKeys[i * 8 + j] = ((randomBytes[i] & (1 << j)) != 0);
            }
        }
    }
}
```
- [Location in source code](https://github.com/PlagueVRC/AntiRip/blob/3d159a8fad7e553df65b6828762320b9debc1cb2/Scripts/KannaProteccRoot.cs#L497)

You don't have to make these changes, I just thought it would make the code a little higher quality and more secure.
Either way I hope you have an amazing day and I believe you are an amazing person for making this project!

**Comment by MistressPlague** [comment]
Hi; in debugging it seems it is already disposed when the script's source stack is finished, I will contribute said fix regardless.
As for the latter, I personally don't find it any more understandable for me, but to be fair that is a fairly subjective one.

Thank you for helping out!

**Comment by w200338** [comment]
I'll gladly explain the second part. The RNGCryptoServiceProvider is purpose-made for generating cryptographically secure randomness which is used for things like secret keys, salts etc. The code example is definitely not as readable as it could be with some comments. It does the following:
1. Create an array of four bytes
2. Pass the array to RNGCryptoServiceProvider to fill it with random bytes
3. Loop over every bit inside the array of random bytes and fill the _bitArray with them

That last step is done by sliding a bitmask over the every byte and checking if a specific bit is 0 (false) or 1 (true).
- (1 << j): create bitmask where one bit is 1 and all the rest is 0
- randomBytes[i] & (1 << j): apply bitmask to one of the random bytes
- (randomBytes[i] & (1 << j)) != 0: if it's anything but 0 (the bitmask and random byte shared a 1 bit in the same position) it's true
```
step:       1          2          3          4
random:  01000101   01000101   01000101   01000101
mask:    00000001   00000010   00000100   00001000
result:  00000001   00000000   00000100   00000000
boolean:   true      false       true      false
```

Looking at it, it may be clearer to write this:
```cs
public void GenerateNewKey()
{
    using (var rng = new RNGCryptoServiceProvider())
    {
        byte[] randomBytes = new byte[4];
        rng.GetBytes(randomBytes);
        int randomNumber = BitConverter.ToInt32(randomBytes);

        for (int i = 0; i < 32; i++)
        {
            _bitKeys[i] = ((randomNumber & (1 << i)) != 0);
        }
    }
}
```

**Comment by MistressPlague** [comment]
Like said before though, this does fall into subjectivity. To me, this makes it more vague, as I find standardized math; even if longer, easier to read than bitshifting. The only type of people who understand bitshifting already would not have issues with the looping alternative. Due to such, this part is wontfix, as it is too subjective overall to take either side objectively, so it falls to my subjective status.

Thank you though.
