### ISSUE TITLE
Would it be possible to write the encryption key over osc instead of htrough unity?

### ISSUE THREAD

**Issue by kruemmelbande** [PlagueVRC/AntiRip#4]
Im assuming here, that the encryption key is in a parameter. If so, it should be possible in theory, to just use a small osc program, to set your encryption key, so in case you reset or something like that, you dont have to open unity and restart your vrchat.

I could be totally wrong in how this works, but i think it might be a good idea to look into it.

**Comment by MistressPlague** [comment]
This is already on the roadmap, please read such before making an issue.

As for the security point, not correct; past and present. It never had a OSC tool as the past project as it is too much for too little.

I'm fine with doing it, but it is low priority.

The roadmap can be found at the bottom-ish of the readme.
