### ISSUE TITLE
Poiyomi shaders don't like Water

### ISSUE THREAD

**Issue by C0D3-M4513R** [PlagueVRC/AntiRip#6]
Encrypted Poiyomi shaders will blur Water waves on maps with water present according to where the obfuscated mesh would be (this is with the person as a friend even).
This effect is most pronounced on avatars with high Distortion Ratios and Maps with Water.
I've had multiple people report this to me now.

Pictures pending. Too drunk and late for me right now.

**Comment by MistressPlague** [comment]
https://trello.com/c/JGAiY42D/16-worlds-that-overlay-the-mesh-via-reading-triangles-will-fail-and-only-apply-over-where-the-encrypted-mesh-would-be
https://trello.com/c/OWCVCXqZ/15-shadow-version-of-the-mesh-is-never-decrypted
