### ISSUE TITLE
Fallback system

### ISSUE THREAD

**Issue by babo4d** [PlagueVRC/AntiRip#9]
> For a user to see your avatar properly in VRChat, they must have your avatar fully shown. Shaders, animations and all. You are invisible otherwise.

A fallback system might help here. Thanks.

**Comment by MistressPlague** [comment]
A fallback avatar / quest avatar is rippable. I will not support something that user error can then lead to them having their content ripped.

**Comment by babo4d** [comment]
Not related to quest avatars or performance fallback. I'm suggesting a custom fallback system that would let you optionally assign another avatar (that you don't care about exposing) to show initially in case animations are disabled, instead of just being invisible. 

I would think most users would want this as an option rather than being forced to be invisible to the part of the population with animations disabled.

**Comment by MistressPlague** [comment]
That is not viable nor is ease of use. The viewpoint would be wrong among numerous other issues. I feel you had a burst idea without in depth thought to it.
